# Generated by Django 3.2.6 on 2021-11-07 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('postCode', models.IntegerField()),
                ('addressL1', models.CharField(max_length=64)),
                ('addressL2', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=256)),
                ('category', models.CharField(choices=[('White Bread', 'White Bread'), ('Country Bread', 'Country Bread'), ('Oat Porridge Bread', 'Oat Porridge Bread'), ('Semolina Bread', 'Semolina Bread'), ('100% Rye Bread', '100% Rye Bread'), ('Focaccia', 'Focaccia'), ('Toast Bread', 'Toast Bread'), ('Sweet Brioche', 'Sweet Brioche')], max_length=64)),
                ('tel', models.IntegerField()),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
