# Generated by Django 3.2.6 on 2021-11-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_orders_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='category',
            new_name='breadType',
        ),
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.CharField(choices=[('$3.5', '$3.5'), ('$3.9', '$3.9'), ('$4.0', '$4.0'), ('$4.5', '$4.5'), ('$3.5', '$3.5'), ('$3.8', '$3.8'), ('$2.5', '$2.5'), ('$7.5', '$7.5')], default='$3.5', max_length=64),
        ),
    ]
