# Generated by Django 3.2.6 on 2021-11-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_auto_20211113_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
