# Generated by Django 3.2.6 on 2021-11-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_alter_orders_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
