# Generated by Django 3.2.6 on 2021-11-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_alter_orders_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
