# Generated by Django 3.2.6 on 2021-09-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Listings',
        ),
    ]
