# Generated by Django 3.2.6 on 2021-09-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_listing_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.IntegerField(choices=[('Fashion', 'Fashion'), (2, 'Toys'), (3, 'Electronics'), (4, 'Home'), (5, 'Other')]),
        ),
    ]
