# Generated by Django 3.2.6 on 2021-09-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='owner',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='saved_item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='saved_item',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
