# Generated by Django 3.2.6 on 2021-09-15 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210915_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='saved_item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='saved_item',
            field=models.ManyToManyField(blank=True, related_name='items', to='auctions.Listings'),
        ),
    ]
