# Generated by Django 3.2.6 on 2021-09-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_watchlist_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='saved_item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='saved_item',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
