# Generated by Django 3.2.6 on 2021-09-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_watchlist_cross_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='image_url',
            field=models.URLField(default=None, max_length=124),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
