# Generated by Django 3.2.6 on 2021-09-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210916_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='listing_id',
            field=models.IntegerField(default=None),
        ),
    ]
