# Generated by Django 3.2.6 on 2021-09-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_comments_listing_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='listing_id',
            new_name='comment_for_id',
        ),
    ]
