# Generated by Django 3.2.6 on 2021-09-17 07:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_rename_listing_id_comments_comment_for_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='desired_bid',
            field=models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='bids',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bids',
            name='starting_bid',
            field=models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
