# Generated by Django 3.2.6 on 2021-09-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210917_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='starting_bid',
        ),
    ]
