# Generated by Django 3.2.6 on 2021-09-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_listings_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='winner',
            field=models.IntegerField(default=0),
        ),
    ]
