# Generated by Django 3.2.6 on 2021-09-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_listings_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='winner',
            new_name='winner_id',
        ),
    ]
