# Generated by Django 3.2.6 on 2021-09-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_rename_winner_listings_winner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='winner_id',
        ),
        migrations.AddField(
            model_name='bids',
            name='winner_id',
            field=models.IntegerField(default=0),
        ),
    ]
