# Generated by Django 3.2.6 on 2021-09-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20210918_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='winner_id',
        ),
        migrations.AddField(
            model_name='bids',
            name='won_item_id',
            field=models.IntegerField(default=0),
        ),
    ]
