# Generated by Django 3.2.7 on 2021-10-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='MyPost',
        ),
    ]
