# Generated by Django 3.2.7 on 2021-10-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_post_mypost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyPost',
            new_name='MyPosts',
        ),
    ]
